# Generated by Django 4.0.4 on 2022-12-06 08:11

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='برند')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='آدرس url')),
                ('meta_description', models.TextField(max_length=300, verbose_name='توضیحات متای صفحه برند')),
                ('meta_keywords', models.TextField(max_length=300, verbose_name='کلمه های کلیدی صفحه برند')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='آدرس URL دسته بندی')),
                ('status', models.BooleanField(default=True, verbose_name='انتشار')),
                ('position', models.IntegerField(verbose_name='موقعیت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='تصویر دسته بندی')),
                ('meta_description', models.TextField(max_length=300, verbose_name='توضیحات متای صفحه دسته بندی')),
                ('meta_keywords', models.TextField(max_length=300, verbose_name='کلمه های کلیدی صفحه دسته بندی')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category', verbose_name='زیر دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'محل قرار گیری محصول',
                'verbose_name_plural': 'محل های قرار گیری محصولات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('english_title', models.CharField(max_length=255, verbose_name='عنوان به انگلیسی')),
                ('window_title', models.CharField(max_length=255, verbose_name='عنوان در مرورگر')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='آدرس URL')),
                ('weight', models.PositiveIntegerField(verbose_name='وزن به گرم')),
                ('unit_price', models.PositiveBigIntegerField(verbose_name='قیمت واحد')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='تخفیف')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='product', verbose_name='تصویر اصلی')),
                ('image_alt', models.CharField(max_length=255, verbose_name='متن جایگزین تصویر اصلی')),
                ('is_available', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده / نشده')),
                ('size_and_color', models.CharField(choices=[('None', 'ندارد'), ('size', 'سایز'), ('color', 'رنگ'), ('both', 'سایز و رنگ')], default='None', max_length=100, verbose_name='سایز و رنگ')),
                ('sell', models.PositiveIntegerField(default=0)),
                ('meta_description', models.TextField(max_length=300, verbose_name='توضیحات متای محصول')),
                ('meta_keywords', models.TextField(max_length=300, verbose_name='کلمه های کلیدی محصول')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_products', to='store.brand', verbose_name='برند')),
                ('category', models.ManyToManyField(related_name='products', to='store.category', verbose_name='دسته بندی')),
                ('favourite', models.ManyToManyField(blank=True, related_name='favourites_user', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='store.position', verbose_name='محل قرار گیری')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایز ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='آدرس URL')),
                ('meta_description', models.TextField(max_length=300, verbose_name='توضیحات متای صفحه تگ')),
                ('meta_keywords', models.TextField(max_length=300, verbose_name='کلمه های کلیدی صفحه تگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('v_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد موجود')),
                ('unit_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت واحد')),
                ('discount_variant', models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف')),
                ('color_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant', to='store.product', verbose_name='محصول')),
                ('size_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'انواع محصولات',
                'verbose_name_plural': 'نوع محصول',
            },
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان')),
                ('characteristic', models.CharField(blank=True, max_length=150, null=True, verbose_name='مشخصه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specifications', to='store.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصه محصول',
                'verbose_name_plural': 'مشخصات محصول',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(related_name='products', to='store.tag', verbose_name='تگ'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'گالری محصولات',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='کامنت')),
                ('rate', models.PositiveIntegerField(default=1, verbose_name='امتیاز به محصول')),
                ('is_recommended', models.BooleanField(default=True, verbose_name='توصیه به خرید')),
                ('status', models.CharField(choices=[('need_approve', 'در انتظار تایید'), ('approved', 'تایید شده'), ('not_approved', 'تایید نشده')], default='need_approve', max_length=20, verbose_name='وضعیت')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('comment_dislike', models.ManyToManyField(blank=True, related_name='com_dislike', to=settings.AUTH_USER_MODEL, verbose_name='دیسلایک کامنت')),
                ('comment_like', models.ManyToManyField(blank=True, related_name='com_like', to=settings.AUTH_USER_MODEL, verbose_name='لایک کامنت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
    ]
