# Generated by Django 4.0.4 on 2022-12-06 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=250, verbose_name='نام')),
                ('last_name', models.CharField(max_length=250, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='ایمیل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user-images', verbose_name='تصویر کاربر')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='شهر')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='لطفا یک شماره همراه معتبر وارد کنید.', regex='^[0][9]\\d{9}$')], verbose_name='شماره تلفن')),
                ('post_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='کد پستی')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='آدرس')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدیر')),
                ('is_news_letter', models.BooleanField(default=False, verbose_name='عضویت در خبرنامه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('is_verify', models.BooleanField(default=False, verbose_name='تایید شده / نشده')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
                ('is_editor', models.BooleanField(default=False, verbose_name='نویسنده ارشد')),
                ('has_setting_access', models.BooleanField(default=False, verbose_name='دسترسی به تنظیمات')),
                ('is_writer', models.BooleanField(default=False, verbose_name='نویسنده')),
                ('temp_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد موقت')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
