# Generated by Django 4.0.4 on 2022-12-06 08:11

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان مقاله')),
                ('article_browser_title', models.CharField(max_length=60, unique=True, verbose_name='آدرس سایت در مرورگر')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='آدرس url')),
                ('image', models.ImageField(upload_to='images/blog-header/', verbose_name='تصویر شاخص')),
                ('image_alt', models.CharField(max_length=200, verbose_name='متن جایگزین تصویر')),
                ('status', models.CharField(choices=[('article', 'مقاله'), ('news', 'خبر'), ('video', 'فیلم')], default='article', max_length=10, verbose_name='نوع محتوا')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات مقاله')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
                ('has_video', models.BooleanField(default=False, verbose_name='شامل کلیپ است')),
                ('meta_description', models.TextField(max_length=300, verbose_name='توضیحات متای صفحه مقاله')),
                ('meta_keywords', models.TextField(max_length=300, verbose_name='کلمه های کلیدی صفحه مقاله')),
                ('article_robots', models.CharField(blank=True, default='index,follow', max_length=100, null=True, verbose_name='تگ robots')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='آدرس url')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش / عدم نمایش')),
                ('meta_description', models.TextField(max_length=300, verbose_name='توضیحات متای صفحه تگ')),
                ('meta_keywords', models.TextField(max_length=300, verbose_name='کلمه های کلیدی صفحه تگ')),
            ],
            options={
                'verbose_name': 'تگ / برچسب',
                'verbose_name_plural': 'تگ ها / برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='کامنت')),
                ('is_reply', models.BooleanField(default=False, verbose_name='آیا پاسخ دارد؟')),
                ('is_published', models.BooleanField(default=True, verbose_name='وضعیت انتشار')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='blog.article', verbose_name='محتوا')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_blog_comments', to='blog.blogcomment', verbose_name='پاسخ به کامنت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='آدرس url')),
                ('blog_category_meta_description', models.TextField(blank=True, max_length=200, null=True, verbose_name='توضیحات متا')),
                ('blog_category_meta_keywords', models.TextField(blank=True, max_length=200, null=True, verbose_name='کلمه های کلیدی')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش / عدم نمایش')),
                ('meta_description', models.TextField(max_length=300, verbose_name='توضیحات متای صفحه دسته بندی')),
                ('meta_keywords', models.TextField(max_length=300, verbose_name='کلمه های کلیدی صفحه دسته بندی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.blogcategory', verbose_name='زیر دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='article', to='blog.blogcategory', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='article', to='blog.blogtag', verbose_name='تگ / برچسب'),
        ),
    ]
