# Generated by Django 4.0.4 on 2022-12-06 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مقایسه')),
                ('title_admin', models.CharField(max_length=100, verbose_name='عنوان مقایسه برای نمایش در ادمین')),
            ],
            options={
                'verbose_name': 'عنوان مقایسه',
                'verbose_name_plural': 'عنوان های مقایسه',
            },
        ),
        migrations.CreateModel(
            name='CompareSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=100, verbose_name='عنوان اول')),
                ('title_2', models.CharField(max_length=100, verbose_name='عنوان دوم')),
                ('compare_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_specifications', to='compare.comparetitle', verbose_name='عنوان مقایسه')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی ها محصول',
            },
        ),
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_compares', to='store.product', verbose_name='محصول')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_compares', to='compare.comparetitle', verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'مقایسه',
                'verbose_name_plural': 'مقایسه ها',
            },
        ),
    ]
