# Generated by Django 4.0.4 on 2022-12-06 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان')),
                ('status', models.CharField(choices=[('open', 'باز'), ('close', 'بسته')], default='open', max_length=10, verbose_name='وضعیت تیکت')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ticket', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
        migrations.CreateModel(
            name='TicketUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان')),
                ('content', models.TextField(blank=True, null=True, verbose_name='متن تیکت کاربر')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='متن پاسخ ادمین')),
                ('ticketUserStatus', models.CharField(choices=[('in_progress', 'در حال بررسی'), ('answered', 'پاسخ داده شده'), ('not_received', 'ارسال شده')], default='not_received', max_length=20, verbose_name='وضعیت این تیکت')),
                ('content_created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال تیکت')),
                ('reply_created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='تاریخ ارسال تیکت')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_ticketUser', to='ticket.ticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'جزییات تیکت',
                'verbose_name_plural': 'جزییات تیکت ها',
            },
        ),
    ]
