# Generated by Django 4.0.4 on 2022-12-06 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='کد پیگیری')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('address', models.CharField(max_length=250, verbose_name='آدرس')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='تخفیف')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت')),
                ('admin_note', models.CharField(blank=True, max_length=150, verbose_name='یادداشت مدیر')),
                ('order_description', models.TextField(blank=True, max_length=500, verbose_name='توضیحات سفارش')),
                ('status', models.CharField(choices=[('P', 'پرداخت شده'), ('S', 'در حال ارسال'), ('R', 'تحویل داده شده'), ('N', 'پرداخت نشده')], max_length=20, verbose_name='وضعیت سفارش')),
                ('shipping_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='هزینه حمل و نقل')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.cities', verbose_name='شهر')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.provinces', verbose_name='استان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_guarantee', models.CharField(blank=True, max_length=200, null=True, verbose_name='گارانتی کنسول')),
                ('controller_guarantee', models.CharField(blank=True, max_length=200, null=True, verbose_name='گارانتی دسته')),
                ('unit_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت واحد بدون تخفیف')),
                ('unit_price_with_discount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت واحد با تخیف')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='تخفیف')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت تمام شده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_orders', to='order.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.variants', verbose_name='نوع محصول')),
            ],
            options={
                'verbose_name': 'جزییات سفارش',
                'verbose_name_plural': 'جزییات سفارش ها',
            },
        ),
    ]
